### ISSUE TITLE
Just Getting Started but I have Used Bela before Today

### ISSUE THREAD

**Issue by silver2row** [BelaPlatform/bela-image-builder#105]
Hello,

I have used Bela and participated in the forums before today. I can sign in to the Board BBB/Bela and use the Cape almost...

1. The board is not allowing me to use https://github.com/silver2row/Bela_Misc with the Klingon Tone generation...
2. I have time to build images if necessary.
3. I see that Linux is used and specific parts attracted my senses. 
a. Updating to newer kernels
b. Updating to newer images with other OS types may be made
c. I can supply ideas in time but need a start

The reason I am reaching out is because I want to use Bela and start to use it more. I would like to help. 

Seth

P.S. I read recently the bela-iree-container scripts and was going to try them out. First, I would like to make my older scripts from transmogrifox work. I put in my ideas so far at the forums. If you need particular help with the builds, please let me know. I have a pretty sturdy computer over here with many cores. I can probably ruin some core trying to build over and over if necessary!

**Comment by silver2row** [comment]
I was using linux-evl and libevl to set up. Is this correct? Should I use those source scripts and handle getting xenomai4 set up this way to port it to an arch. that I use to get Bela to work on it?

I know it is not this easy or easy at all. I am just building and trying out their builds to supply some motive to get invovled.

Seth

**Comment by giuliomoro** [comment]
sorry Seth I think I missed the first post.    

> The board is not allowing me to use https://github.com/silver2row/Bela_Misc with the Klingon Tone generation...

what does it mean "is not allowing me to use" ?

>I was using linux-evl and libevl to set up. Is this correct? S

We are using Xenomai 3, so evl is out of the picture at the moment

**Comment by silver2row** [comment]
The first post was a bit off. The use of the lib works fine now. 

So, Xenomai 3 instead. Okay. I have been building for linux-evl and libevl. Blah. Okay. I will research more. Thank you.

Seth

**Comment by silver2row** [comment]
Okay...so Cobalt and Mercury is in. Okay, what is this: ` --ipipe=ipipe-core-X.Y.Z-x86-NN.patch` . 

From what I have read, this `ipipe` is an older format of their `firmware`. I see the .patch suffix and file type. Where is the .patch or is that not given? 

Seth

P.S. I was going to build the dovetail image under Cobalt within the Xenomai. No go for now...

```
Are you allowed to supply any help in this realm?
```

If so, awesome. If not, I completely understand. I will keep trying to provide my own patch.

**Comment by silver2row** [comment]
Anyway...I am sure everyone is busy now. I am closing this request. Thank you for participating. 

Seth
