### ISSUE TITLE
kernel CONFIG flags

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/bela-image-builder#16]
<a href="https://github.com/giuliomoro"><img src="https://avatars3.githubusercontent.com/u/4260604?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [giuliomoro](https://github.com/giuliomoro)**
_Tuesday Apr 25, 2017 at 01:56 GMT_
_Originally opened as https://github.com/LBDonovan/image-builder/issues/16_

----

Please enable
CONFIG_XENO_DRIVERS_RTIPC

Otherwise you cannot create pipes! (RTIPC is real-time-inter-process-communication).
Perhaps other things need to be enabled as well, check the 3.8.13 kernel config for hints on _XENO_ flags to enable:
https://github.com/BelaPlatform/Bela/issues/171#issuecomment-254467844

**Comment by LBDonovan** [comment]
The kernel does not currently compile with this flag set, it fails with `implicit function declaration` somewhere in the xenomai code.

**Comment by LBDonovan** [comment]
should enable `CONFIG_USB_CONFIGFS_F_UAC1` and `CONFIG_USB_CONFIGFS_F_UAC2` to see if we can turn Bela into a USB sound card
