### ISSUE TITLE
DHCP screws up host computer IP

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/bela-image-builder#18]

**Comment by giuliomoro** [comment]
Is this fixed for good? did you find the reason?

**Comment by LBDonovan** [comment]
Seems to be - I am using a different dhcp server with a different configuration now. It's kind of a miracle the previous one worked at all to be honest - this one seems a lot more stable.

**Comment by giuliomoro** [comment]
I occasionally see it popping up with `169....` but within a second or so it goes back to `192.168.7.1` ...
