### ISSUE TITLE
Can't login with root

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/bela-image-builder#2]
<a href="https://github.com/LBDonovan"><img src="https://avatars1.githubusercontent.com/u/16209658?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [LBDonovan](https://github.com/LBDonovan)**
_Sunday Apr 16, 2017 at 17:53 GMT_
_Originally opened as https://github.com/LBDonovan/image-builder/issues/2_

----

There's no root password but ssh doesn't let you login as root, you have to login as user 'bela' password 'a' then `sudo su`. Probably an issue with the ssh config

**Comment by giuliomoro** [comment]
<a href="https://github.com/giuliomoro"><img src="https://avatars3.githubusercontent.com/u/4260604?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [giuliomoro](https://github.com/giuliomoro)**
_Monday Apr 24, 2017 at 23:42 GMT_

----

edit `/etc/ssh/sshd_config` to allow `root` login over `ssh` and also to allow empty password:
```
32c32
< #PermitRootLogin prohibit-password
---
> PermitRootLogin yes
57c57
< #PermitEmptyPasswords yes
---
> PermitEmptyPasswords yes
```

Note: apply this change AFTER you installed `openssh-server`

**Comment by giuliomoro** [comment]
@LBDonovan where is a good place to add patches like this in the build script?
Shall I create a `patches/` folder and apply them in `build-bela.sh` at the end of 
```
if [ -f ${NO_ROOTFS} ] ; then
```
perhaps?

**Comment by LBDonovan** [comment]
For system configuration files like dhdpd_config etc I have been keeping a full copy of the new file in `misc/` and then cp'ing it into the chroot in `pre-chroot.sh`. It would probably be better to keep and apply patches but I always worry that if the target file changes (e.g. debootstrap changes what it creates) the patch won't get applied properly. It's up to you really! I would apply the patches in a post-chroot script, or alternatively just in `build_bela.sh` after calling `chroot.sh`.

**Comment by LBDonovan** [comment]
Did you get root ssh access working?

**Comment by giuliomoro** [comment]
besides from the changes above, you should also set 

```
UsePAM no
```

**Comment by giuliomoro** [comment]
But 3.8.13 has `UsePAM` enabled and still you can login as `root` with no password and no keys.
May be something has changed with the OpenSSH version?

Either way, the diff between the `grep -v "^#" filename | sort -u` of the two versions of `/etc/pam.d/sshd` is as follows:

```
 diff pam.3.8.13.sorted pam.sorted
3,4d2
< auth       required     pam_env.so # [1]
< auth       required     pam_env.so envfile=/etc/default/locale
8a7
> session    optional     pam_keyinit.so force revoke
10,11c9,12
< session    optional     pam_motd.so # [1]
< session    optional     pam_motd.so  motd=/run/motd.dynamic noupdate
---
> session    optional     pam_motd.so  motd=/run/motd.dynamic
> session    optional     pam_motd.so noupdate
> session    required     pam_env.so # [1]
> session    required     pam_env.so user_readenv=1 envfile=/etc/default/locale
12a14,16
> session    required     pam_loginuid.so
> session [success=ok ignore=ignore module_unknown=ignore default=bad]        pam_selinux.so close
> session [success=ok ignore=ignore module_unknown=ignore default=bad]        pam_selinux.so open
```

**Comment by giuliomoro** [comment]
right now you can login with root out of the box (see 66159cd75438e1196afee19511d340469dd245c6). Not sure whether having PAM disabled is good or bad.
