### ISSUE TITLE
The `build_bela.sh` script requires `root` privileges

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/bela-image-builder#20]
... which is pretty annoying.
For instance, it creates all the files in `downloads/` with `root` as the owner ...
What does it need `sudo` for?

**Comment by LBDonovan** [comment]
It needs it for a bunch of things: debootstrap, chroot, copying stuff into the chroot, creating the image, mounting the image, editing the image etc etc etc. If you run it not as root it will ask you for the root password at least three times so you have to sit there and watch it, which is more annoying imo.

**Comment by giuliomoro** [comment]
Probably closed by https://github.com/BelaPlatform/bela-image-builder/commit/ce04cf07351775f3ddb5baad68d2cb84065c0285.
