### ISSUE TITLE
`--cached-fs` option ignores path

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/bela-image-builder#21]
what is that supposed to do?

**Comment by LBDonovan** [comment]
Oh yeah I didn't get around to implementing that properly.

At the moment I do this manually, to avoid redoing the whole debootstrap image if I have just changed things in the chroot scripts:
- Add `exit` in `build_bela.sh` just before calling `pre_chroot.sh` and run it
- sudo cp -a rootfs c_rootfs
- Remove `exit`
- run `build_bela.sh` with `--cached-fs`

This could be scripted I guess
