### ISSUE TITLE
libllvm3.9 and libclang1-3.9 get installed

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/bela-image-builder#22]
```
I: Retrieving libclang1-3.9 1:3.9.1-8
I: Validating libclang1-3.9 1:3.9.1-8
I: Retrieving libllvm3.9 1:3.9.1-8
I: Validating libllvm3.9 1:3.9.1-8
```
why? What does depend on them? Note we are manually installing `clang` 4.0

**Comment by LBDonovan** [comment]
No idea. I would guess maybe Bison or Flex as I don't know what they are but they are required to build the custom dtc.

**Comment by giuliomoro** [comment]
I promoted this to expected behaviour, avoiding clang 4 altogether. We install 3.9 on the board from `apt-get` and that's it. Safer, better. (Also removing the 3.8 that was installed as default).
