### ISSUE TITLE
You don't get kicked out of `ssh` after you do `halt`

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/bela-image-builder#24]
... so you have to remember the old trick "return, tilde, dot" in order to get back your terminal.

**Comment by LBDonovan** [comment]
can this be fixed?

**Comment by giuliomoro** [comment]
I guess so.

**Comment by LBDonovan** [comment]
The solutions I have found require `UsePAM yes`

**Comment by giuliomoro** [comment]
that's boring.

**Comment by giuliomoro** [comment]
well I guess
```
alias halt="echo "Shutting down"; sleep 2 && halt & exit"
```
in `~/.bashrc`
would simulate 90% of what we need

**Comment by LBDonovan** [comment]
b17adf3

**Comment by giuliomoro** [comment]
reopened :(
