### ISSUE TITLE
`dtoverlay`

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/bela-image-builder#28]
> `dtoverlay`
>  is a command line utility that loads and removes overlays while the system is running, as well as listing the available overlays and displaying their help information

Not sure if this is a pi only thingy.
https://www.raspberrypi.org/documentation/configuration/device-tree.md#part3.5

**Comment by LBDonovan** [comment]
Yeah I think this is a pi thing, it sounds like `config-pin` does something pretty similar on the bbb.

What's that techno-world commit about?

**Comment by giuliomoro** [comment]
I think `config-pin` only allows to add overlays, not removing them?
