### ISSUE TITLE
Provide upgrade path for older BBB

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/bela-image-builder#40]
so that they can boot from the SD card !

**Comment by giuliomoro** [comment]
This could be as simple as "screw up your eMMC bootloader", but hopefully a bit nicer

**Comment by LBDonovan** [comment]
Do you have an older bbb that doesn't currently boot we can test with? I think I have just found a totally non-destructive way to do this

**Comment by giuliomoro** [comment]
plenty
