### ISSUE TITLE
where should the dts files live?

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/bela-image-builder#47]
@LBDonovan I forked `dtb-rebuilder` to https://github.com/BelaPlatform/dtb-rebuilder: using this from now on.

BUT, it is pretty annoying to have to copy the files over from BelaPlatform/Bela to here.
We should decide where to keep them in the first place and only always keep them there.

I'd suggest keeping them in the Bela repo and copying them over to the `dtb-rebuilder` folder when compiling them in `chroot`. I don't see any concrete advantage in keeping them in `dtb-rebuilder` or hope for a merge into mainline (or beagleboard.org) anyhow, given that  - to make use of those - someone needs to have a Bela cape and a dedicated image anyhow.

**Comment by LBDonovan** [comment]
These now live in dtb-rebuilder. They need to be cleaned from `resources`.

**Comment by giuliomoro** [comment]
In `resources/` we will leave the dtbs for wheezy. Not sure if there is anything different/incompatible, but I mostly don't care as they shall not change.
