### ISSUE TITLE
Does not boot on BeagleBone Black Wireless

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/bela-image-builder#57]
Flashed f2bef87a98df13c9ba7b056a8d76e29923ba12ac on SD card, powering up the BBBWireless, it boots from the eMMC providing the log below.
If I hold press the usr button at boot, it boots from the SD card.
On BeagleBone Black (non-wireless), it boots fine.

Previous releases of the image used to boot fine on the BBBW. Not sure which is the last one I tried, most likely around d9b919adc2e2315e6700ab5bdf9ae7efb5dcebb1

```
U-Boot SPL 2016.11-rc3-00002-g73df7f7 (Nov 04 2016 - 15:20:36)
Trying to boot from MMC2


U-Boot 2016.11-rc3-00002-g73df7f7 (Nov 04 2016 - 15:20:36 -0500), Build: jenkins-github_Bootloader-Builder-479

CPU  : AM335X-GP rev 2.1
I2C:   ready
DRAM:  512 MiB
Reset Source: Power-on reset has occurred.
MMC:   OMAP SD/MMC: 0, OMAP SD/MMC: 1
Using default environment

Board: BeagleBone Black
Model: BeagleBone Black Wireless
<ethaddr> not set. Validating first E-fuse MAC
Net:   eth0: MII MODE
Could not get PHY for cpsw: addr 0
cpsw
Press SPACE to abort autoboot in 2 seconds
board_name=[BBBW] ...
Card did not respond to voltage select!
Card did not respond to voltage select!
Card did not respond to voltage select!
gpio: pin 56 (gpio 56) value is 0
gpio: pin 55 (gpio 55) value is 0
gpio: pin 54 (gpio 54) value is 0
gpio: pin 53 (gpio 53) value is 1
Card did not respond to voltage select!
Card did not respond to voltage select!
switch to partitions #0, OK
mmc1(part 0) is current device
Scanning mmc 1:1...
gpio: pin 56 (gpio 56) value is 0
gpio: pin 55 (gpio 55) value is 0
gpio: pin 54 (gpio 54) value is 0
gpio: pin 53 (gpio 53) value is 1
switch to partitions #0, OK
mmc1(part 0) is current device
gpio: pin 54 (gpio 54) value is 1
Checking for: /uEnv.txt ...
Checking for: /boot.scr ...
Checking for: /boot/boot.scr ...
Checking for: /boot/uEnv.txt ...
gpio: pin 55 (gpio 55) value is 1
1234 bytes read in 33 ms (36.1 KiB/s)
Loaded environment from /boot/uEnv.txt
Checking if uname_r is set in /boot/uEnv.txt...
gpio: pin 56 (gpio 56) value is 1
Running uname_boot ...
loading /boot/vmlinuz-4.4.30-ti-r64 ...
8644992 bytes read in 575 ms (14.3 MiB/s)
loading /boot/dtbs/4.4.30-ti-r64/am335x-boneblack-wireless.dtb ...
64988 bytes read in 47 ms (1.3 MiB/s)
loading /boot/initrd.img-4.4.30-ti-r64 ...
5157981 bytes read in 358 ms (13.7 MiB/s)
debug: [console=ttyO0,115200n8 root=UUID=ac4731db-c4db-463f-9129-07e6746b98ba ro rootfstype=ext4 rootwait coherent_pool=1M quiet cape_universal=enable] ...
debug: [bootz 0x82000000 0x88080000:4eb45d 0x88000000] ...
## Flattened Device Tree blob at 88000000
   Booting using the fdt blob at 0x88000000
   Loading Ramdisk to 8fb14000, end 8ffff45d ... OK
   Loading Device Tree to 8fb01000, end 8fb13ddb ... OK

Starting kernel ...
```

**Comment by giuliomoro** [comment]
by the time we got to 44c0640235461153aedd87ef4e8a6bd49c9a7fd8, this has been fixed somehow

**Comment by SonicInteraction** [comment]
This still seems to be an issue here. Almost all of our 25 belas are presenting boot problems, among other instability issues. These problems do not seem to present when using Beaglebone Black.

**Comment by martin-minovski** [comment]
Same issue here. If I disconnect/reconnect the USB cable repeatedly, it boots eventually - regardless of available current.

**Comment by giuliomoro** [comment]
If what you are experiencing is the blue power light blinking briefly as you plug in the cable, and then immediately switching off again, I think this has to do with power consumption and not with the image itself.
What I speculate is that the combined inrush current of the CPU, Wireless module and Bela cape exceeds the capability of the power management IC on the BeagleBone.
In this sense, plugging/unplugging/re-plugging in a quick succession should take advantage of some of the capacitors being still partially charged.
These are just my speculations, though. I think the [beagleboard google group](https://groups.google.com/forum/#!forum/beagleboard) would be a better place to search for answers, and help, on this topic.

(incidentally, the original issue I opened here was about the board booting from the eMMC instead of the SD card, which is a different story)

**Comment by SonicInteraction** [comment]
We have this issue on perhaps a third of the units at AAU, we also believe
it is a power management issue on beaglebone, but we have not tried the
pluggin in/unplugging trick.
Best Regards
Peter Williams
61 39 36 00
www.peterwilliams.dk

**Comment by giuliomoro** [comment]
Have you tried powering from the barrel jack?

**Comment by SonicInteraction** [comment]
We've found significantly fewer issues when powering from the jack.
However, the behaviour in question appears to be erratic in the first place.
