### ISSUE TITLE
Properly handle ctag overlay

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/bela-image-builder#86]
Shall we add the overlay by default to `uEnv.txt` and then whoever wants to use those pins for something else (e.g.:  quadrature encoders) disables it?

Also @henrix what overlay should we use ? We have an old one [here](https://github.com/BelaPlatform/Bela/tree/master/resources/ctag) but I see you have two more in [here](https://github.com/beagleboard/bb.org-overlays/tree/master/src/arm). What happens if we load the 16ch version when only the FACE is available?

**Comment by giuliomoro** [comment]
TODO: enable it by default in `uEnv.txt`.

**Comment by henrix** [comment]
Right, it should be enabled in the uEnv.txt.

For Bela, [this](https://github.com/BelaPlatform/Bela/tree/master/resources/ctag) overlay should be used.
The other overlays are for ALSA.
If the 16ch is enabled, the master board (i.e. face) can be still used as long as the master board is responsible for clock generation.
The first eight channels always correspond to the master board.

**Comment by giuliomoro** [comment]
great. Are there any plans to have that overlay merged into `bb.org-overlays` or shall we maintain it ourselves?

**Comment by henrix** [comment]
I think it's better to maintain it yourself due configuration settings, which are mostly Bela, and not ALSA (i.e. "standard" Linux) related.

**Comment by giuliomoro** [comment]
it is enabled by default as of f1a9720ab0464583a37b49a997c3f942643ec7e9, so closing this.
