### ISSUE TITLE
build_bela.sh: Xenomai repo branch renamed

### ISSUE THREAD

**Issue by jarmitage** [BelaPlatform/bela-image-builder#92]
`stable-v3.0.x` -> `stable/v3.0.x`

**Comment by jarmitage** [comment]
This is listed correctly here:
https://github.com/BelaPlatform/bela-image-builder/blob/2919267fdd262757b8b15a30a1ec0c0cb9feb78d/scripts/downloads.sh#L35

But:
> you need to change it in `bela-image-builder/downloads/ti-linux-kernel-dev/scripts/git.sh`[...] you can only do it after the downloads have been downloaded

**Comment by jarmitage** [comment]
Temp fix:

Change: https://github.com/BelaPlatform/bela-image-builder/blob/master/scripts/downloads.sh#L29
To: `git_clone_address="https://github.com/giuliomoro/ti-linux-kernel-dev"`

And then restart downloads process

**Comment by giuliomoro** [comment]
the [PR](https://github.com/RobertCNelson/ti-linux-kernel-dev/pull/29#issuecomment-441397130) has been merged upstream. Workaround no longer needed.
